### ISSUE TITLE
Update publish status

### ISSUE THREAD

**Issue by MatthMig** [SciCatProject/scicat-ingestor#177]
Facilities will often have their own system to manage the publish status of their proposal, I think we can benefit from a service to ease the ingestion of the publish status.

I have done a suggestion of implementation in those commits:
- https://github.com/SciCatProject/scicat-ingestor/pull/141/commits/cdae5d5dc431441395975b87c6361fb39fc34e10
- https://github.com/SciCatProject/scicat-ingestor/pull/141/commits/7b2c61cab543138dd96e26c0e3dcb09de7be5d51
- https://github.com/SciCatProject/scicat-ingestor/pull/141/commits/df87af5cd28b4cd337398ff61a0d558903e6e807

Corresponding service in SciCatLive services/ingestor/compose.yaml:

```yml
services:
  update-published:
    image: docker.ill.fr/scicat-ill/ingestor:latest
    depends_on:
      backend:
        condition: service_healthy
    env_file: .env
    environment:
      CONFIG_FILE: /app/config/config.sample.json
    volumes:
      - ./config/config.sample.json:/app/config/config.sample.json:ro
    entrypoint: ["/bin/sh", "-c", "while true; do /app/update-published.sh; sleep 86400; done"]
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```
